### ISSUE TITLE
Error when trying to open AddonManager

### ISSUE THREAD

**Issue by DanielBagdasarian** [LuaLS/vscode-lua#157] opened 2024-10-27 10:45 UTC
### Which OS are you using?

Windows

### Expected Behaviour

Enabling MoonLoader. At the moment, it does not work, i.e. its commands are not registered in vs code

### Actual Behaviour

![image](https://github.com/user-attachments/assets/a6e1a8b0-5052-4c34-8520-2b05d257c6c4)
![image](https://github.com/user-attachments/assets/54fd3d11-5286-4c27-893f-cbf5afc616f0)
![image](https://github.com/user-attachments/assets/591bf2de-ecc3-408e-b4ee-5c32fbc6c553)
Although it shows that the extension is installed, it doesn't work.

I also see the following error:

```
[2024-10-27 13:37:17] |   ERROR   |     Filesystem     | Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/bagda/AppData/Roaming/Code/User/globalStorage/sumneko.lua/addonManager/addons/ao/module'
```

### Reproduction steps

1. Press Ctrl+Shift+P
2. Enter >Lua:Open the Add-on Manager
3. See the error from below

### Additional Notes

Everything worked fine before

### Log

An error occurred with the Lua Addon Manager. Please help us improve by reporting the issue ❤️

**Comment by CheezusChrust** [comment] 2024-10-27 17:25
Looks like the same issue as
- #154

**Comment by carsakiller** [comment] 2024-10-28 15:22
This does appear to be a duplicate of #154. It should be fixed by https://github.com/LuaLS/vscode-lua/pull/156.

**Closed by carsakiller** 2024-10-28 15:22 UTC
