### ISSUE TITLE
Lua went wrong 

### ISSUE THREAD

**Issue by MaxDLink** [LuaLS/vscode-lua#83] opened 2023-03-03 02:28 UTC
### Which OS are you using?

MacOS

### Expected Behaviour

went wrong in the background? 

### Actual Behaviour

...

I also see the following error:

```
[2023-03-02 20:27:49] |   ERROR   |         Git        | fatal: not a git repository (or any of the parent directories): .git

```

### Reproduction steps

2. Click '...'
3. See error '...'

**Comment by carsakiller** [comment] 2023-03-03 02:52
Duplicate of https://github.com/LuaLS/vscode-lua/issues/81

**Closed by carsakiller** 2023-03-03 02:52 UTC
