### ISSUE TITLE
Failing to open Addon Manager

### ISSUE THREAD

**Issue by Bilal2453** [LuaLS/vscode-lua#117] opened 2023-04-05 15:39 UTC
### Which OS are you using?

Windows

### Expected Behaviour

When creating and opening a workspace, pressing `Ctrl + Shift + P`, and "Open Addon Manager", the Addon Manager is opened without any errors.

### Actual Behaviour

An error prompt appears:
![image](https://user-images.githubusercontent.com/38175840/230127696-4515d322-3902-4f67-956c-57ed732418d8.png)

### Reproduction steps

1. Make and open a workspace.
2. Press `Ctrl + Shift + P`, "Lua Addon Manager", press Enter.
3. The error should show up.

### Additional Notes

This was tested on the extension version 3.6.18, on Windows. Note that it *only* happens on Windows.
This was not discovered by me, rather it was reported by someone else who was following my instructions. I cannot replicate it myself on Linux.

### Log

No output at all in the Lua Addon Manager dropdown.

**Comment by carsakiller** [comment] 2023-04-05 21:11
Nothing changed that should be causing this. If the command is not found, that means the addon manager is never being initialized. Please make sure the `addonManager.enable` setting is not set to false.

**Comment by Bilal2453** [comment] 2023-04-05 21:22
@carsakiller I too thought it was disabled in the settings, but it doesn't seem like it:
![image](https://user-images.githubusercontent.com/38175840/230214332-235d449f-7177-452c-beae-cea41aba67e1.png)

**Comment by carsakiller** [comment] 2023-04-05 21:23
The rest of the extension works as expected (completion, type checking, etc.)?

**Comment by Bilal2453** [comment] 2023-04-05 21:24
Yes sir.

**Comment by carsakiller** [comment] 2023-04-05 21:34
I will have to look into this at a later time

**Comment by Bilal2453** [comment] 2023-04-05 21:37
Sorry, I can't seem to be able to provide any further debugging info regarding this.   If you look into this and don't find anything, it may not be worth keeping the issue opened.

**Comment by carsakiller** [comment] 2023-04-07 01:53
I am not able to reproduce in `v3.6.18`. Without the output from the VS Code developer console, I cannot find a cause for this problem. If the person following your instructions can provide that, we can reopen this issue, but I'm going to close it for now.

**Closed by carsakiller** 2023-04-07 01:53 UTC
Labels: addon manager
