### ISSUE TITLE
Lua Extension crashes due to not being able to find the .git repo

### ISSUE THREAD

**Issue by taranlu-houzz** [LuaLS/vscode-lua#101] opened 2023-03-06 23:19 UTC
### Which OS are you using?

MacOS

### Expected Behaviour

The extension should not crash on startup.

### Actual Behaviour

The Lua extension started to complain after a recent update to VSCode. I think this either has to do with the fact that my repo is a mono-repo with many sub-projects or that there are symlinks within the repo.

I also see the following error:

```
[2023-03-06 15:14:08] |   ERROR   |         Git        | fatal: not a git repository (or any of the parent directories): .git

```

### Reproduction steps

1. Open VSCode

### Additional Notes

- Filing this since the extension started breaking and it prompted me to file a bug.
- This is a medium sized, mono-repo with a fair number of python subprojects.

#### STARTUP ####
[2023-03-06 15:14:07] |   DEBUG   |     Filesystem     | Created directory at "/Users/----/Library/Application Support/Code/User/globalStorage/sumneko.lua/addonManager"
[2023-03-06 15:14:08] |   ERROR   |         Git        | Failed to checkout repo!
[2023-03-06 15:14:08] |   ERROR   |         Git        | fatal: not a git repository (or any of the parent directories): .git

**Comment by carsakiller** [comment] 2023-03-07 01:23
This is to do with the [new addon manager](https://github.com/LuaLS/lua-language-server/discussions/1965) and seems to be a duplicate of https://github.com/LuaLS/vscode-lua/issues/81. The extension and language server is not crashing, the addon manager is just throwing an error.

**Closed by carsakiller** 2023-03-07 01:23 UTC
Labels: duplicate, addon manager
